enhancement: different library used
xyztek/pandora-hsm pull request #4
Opened 2023-03-28 10:44 UTC by atasen19

2023-03-30 12:13 UTC, mcaneris requested changes

2023-03-30 12:13 UTC, mcaneris commented on scripts/generate.js
> +console.warn('privKey', keys.privateKey)
we shouldn't print the key here.

2023-03-30 12:13 UTC, mcaneris commented on scripts/generate.js
> +await sign(alg, keys, 'data_to_be_signed')
no signing here. this is a generation script.

2023-03-30 12:13 UTC, mcaneris commented on scripts/generate.js
> +await generateCSR(alg, keys)
output CSR to local file.

2023-03-30 12:13 UTC, mcaneris commented on src/csr.js
> +    console.log(csr.toString('pem'))
do not log. return the CSR.

2023-03-30 12:13 UTC, mcaneris commented on src/generator.js
> +    }
do not log

2023-03-30 12:13 UTC, mcaneris commented on src/generator.js
> +    await crypto.certStorage.clear()
do not clear

2023-03-30 12:13 UTC, mcaneris commented on src/generator.js
> +async function generateKeyPair (alg) {
receive slot to create as argument

2023-03-30 12:13 UTC, mcaneris commented on src/generator.js
> +    return { alg, keys, crypto }
why return anything except keys?

2023-03-30 12:13 UTC, mcaneris commented on src/signer.js
> +async function sign (alg, keys, data) {
receive slot to read the key from as argument.

2023-03-30 12:13 UTC, mcaneris commented on src/signer.js
> +  console.log(`Signature: ${signature}`)
do not log.

2023-03-30 12:13 UTC, mcaneris commented on src/signer.js
> +  console.log(`Verification: ${ok}`)
do not log.

2023-03-30 12:13 UTC, mcaneris commented on src/signer.js
> +  console.log(`Verification: ${ok}`)
return signature.

2023-03-30 12:45 UTC, atasen19 commented on src/signer.js
> +async function sign (alg, keys, data) {
I couldn't figure it out how to receive the key from with requested type / or there is no way to do it according to the library's documentation, which means we have to take it as an input.

2023-04-13 10:40 UTC, mcaneris approved these changes

2023-04-13 10:40 UTC, mcaneris commented on src/signer.js
> +    pin: '123456',
read these values from env

2023-04-13 10:46 UTC, merged